apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl-date-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: nl-date-backend
  template:
    metadata:
      labels:
        app: nl-date-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.backend.env.SPRING_DATASOURCE_USERNAME | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.backend.env.SPRING_DATASOURCE_PASSWORD | quote }}
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.backend.env.SPRING_JPA_HIBERNATE_DDL_AUTO | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: nl-date-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: nl-date-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
