apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl-date-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: nl-date-frontend
  template:
    metadata:
      labels:
        app: nl-date-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nl-date-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: nl-date-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
