apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nl-date-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nl-date-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nl-date-mysql
  template:
    metadata:
      labels:
        app: nl-date-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password | quote }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: nl-date-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nl-date-mysql
spec:
  type: ClusterIP
  selector:
    app: nl-date-mysql
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
